package com.trye.catche.finallye;



/** We will get the abnormal termination because of we are not handling the Exception
 * @author SALEEM
 *
 */
public class Test_Without_Try_Catch_04 {
	
	public static void main(String[] args) {
		
		System.out.println("Statement-1");
		System.out.println(10/0);
		System.out.println("Statement-2");

	}//main
	
	

}//class

